# Generated by Django 5.0.4 on 2024-05-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamodel',
            name='cpf',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='agendamodel',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='agendamodel',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
